CREATE TABLE folders (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id UUID REFERENCES folders(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files ADD COLUMN folder_id UUID REFERENCES folders(id) ON DELETE CASCADE;
